---
# Running on parent folder: dc-run test-chromium
# In container, run chromium with command: chromium-browser --disable-dev-shm-usage
version: '3'
services:
    test-chromium:
        image: platbase.com/dev.base:latest
        volumes:
            - ${RUNTIME_DIR}/workspace:/workspace
            - ${RUNTIME_DIR}/data:/data
            #- /tmp/dev-base.ws:/workspace
            #- /tmp/dev-base.data:/data
            - /tmp/.X11-unix:/tmp/.X11-unix
            - /dev/snd:/dev/snd
        environment:
            - DISPLAY=unix$DISPLAY
        privileged: true
