---
# Running on parent folder: dc-run test-chromium-no-sandbox
# NOTE: In container, you must run chromium with command: chromium-browser --no-sandbox --disable-dev-shm-usage
version: '3'
services:
    test-chromium-no-sandbox:
        image: bizobj-container.net/dev/dev.base:latest
        volumes:
            - ${RUNTIME_DIR}/workspace:/workspace
            - ${RUNTIME_DIR}/data:/data
            #- /tmp/dev-base.ws:/workspace
            #- /tmp/dev-base.data:/data
            - /tmp/.X11-unix:/tmp/.X11-unix
            - /dev/snd:/dev/snd
        environment:
            - DISPLAY=unix$DISPLAY
        #privileged: true
