---
# Running on parent folder: dc-start -
version: '3'
services:
    demo-nodejs:
        image: platbase.com/dev.code-server:1.4-3.10.2
        ports:
            - "${PORT1}:8080"
        volumes:
            - ..:/workspace   # Relative path based compose file
            - ${RUNTIME_DIR}/data:/data
            - /tmp/.X11-unix:/tmp/.X11-unix
        environment:
            - DISPLAY=unix$DISPLAY
            - TERM=xterm-256color    # make terminal of VSCode colorful
        #privileged: true
