---
version: '2'
services:
    keystone-dev:
        image: platbase.com/dev.nodejs:6.2.1
        ports:
            - "${PORT1}:8080"
        volumes:
             - /tmp/.X11-unix:/tmp/.X11-unix  # Use host's X
             - ${WORKING_DIR}:/workspace
             - ${DOCKER_BASE}/${COMPOSE_NAME}/nodejs:/data
        environment:
             - TERM=xterm
             - LANG=zh_CN.UTF-8
             - PORT=8080                             # keystone HTTP Port
             - MONGO_URI=mongodb://mongodb/keystone  # keystone mongodb access URL
             - DEVOPS_FIXED_ENVS=PORT MONGO_URI      # Ensure bash in console can use these variables
        links:
             - mongodb
    mongodb:
        image: platbase.com/dev.mongodb:1.0
        volumes:
             - ${DOCKER_BASE}/${COMPOSE_NAME}/mongodb:/data
        environment:
             - TERM=vt100
