---
version: '2'
services:
    react-native-dev:
        image: platbase.com/dev.react-native:1.0
        privileged: true  # Privilege to access host's USB device, important for developing with physical device
        ports:
            - "${PORT1}:8081"
        volumes:
             - /tmp/.X11-unix:/tmp/.X11-unix  # Use host's X
             - /dev/bus/usb:/dev/bus/usb      # Use host's USB device, important for developing with physical device
             - ${WORKING_DIR}:/workspace
             - ${DOCKER_BASE}/${COMPOSE_NAME}/react-native:/data
        environment:
             - TERM=xterm
             - LANG=zh_CN.UTF-8
             - http_proxy=http://docker-host:8123
             - https_proxy=http://docker-host:8123
