---
# Running on parent folder: dc-run -
version: '3'
services:
    test-nodejs:
        image: platbase.com/dev.nodejs:latest
        ports:
            - "${PORT1}:8080"
        volumes:
            - ${RUNTIME_DIR}/workspace:/workspace
            - ${RUNTIME_DIR}/data:/data
            - /tmp/.X11-unix:/tmp/.X11-unix
        environment:
            - DISPLAY=unix$DISPLAY
        #privileged: true
